# This is a TOML document

[database]
addr = "localhost:3306"
user = "test"
charset = "utf8mb4"
flavor = "mysql"

[kafka]
topic = "mySql_test_1"
broker_list = ["127.0.0.1:9092"]
retry = 10
flush = 100

[dump]
mysqldump_path = "/mnt/c/Program Files/MySQL/MySQL Server 8.0/bin/mysqldump.exe"

[[source]]
schema = "test"
tables = ["test_table"]